import { StandardTableView, VerticalBox, LineEdit, HorizontalBox, ListView, CheckBox, Switch } from "std-widgets.slint";
import { MyComboBox, Buttoner } from "my-components.slint";

export struct Row {
    name: string,
    value: float,
    checked: bool,
    timespan: string,
}

export component AddNew inherits Rectangle {
    // Define the dynamic data model
    in property <[Row]> value_list: [
        { name: "test1", value: 10, checked: false, timespan: "Daily" },
        { name: "test2", value: 15, checked: false, timespan: "Daily" },
        { name: "test3", value: 20, checked: true, timespan: "Daily" },
    ];
    VerticalLayout {
        list-view := ListView {
            for element in root.value_list: HorizontalLayout {
                Switch {
                    toggled => {
                        element.checked = self.checked;
                    }

                    text: element.name;
                    checked: element.checked;
                }
            }
        }
        VerticalBox { // Possible Graph later
            height: 100px;
        }
        HorizontalLayout {
            // TextInput fields for new values
            LineEdit {
                width: 2 * parent.width / 4;
                placeholder-text: "New Name";
            }

            LineEdit {
                width: parent.width / 4;
                placeholder-text: "New Value";
            }

            MyComboBox {
                width: parent.width / 4;
            }
        }

        // Button to add a new row
        Buttoner {
            text: "Add Row";
            clicked => {
            
            }
        }
        VerticalBox {
            height: 50px;
        }
    }
}